version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: chats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pms
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
  app:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 challenge_chat.asgi:application"
    volumes:
      - .:/app
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: chats
      DATABASE_USER: postgres
      DATABASE_PASSWORD: pms
      DATABASE_PORT: 5432
      REDIS_HOST: redis
  pgadmin:
    image: dpage/pgadmin4:7
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@chat.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin_pms
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
        
volumes:
  postgres_data:
  redis_data:
  pgadmin_data: